### ISSUE TITLE
Clearing authorship colors fails when no text selected in PAD if there is a HEADING on the first line

### ISSUE THREAD

**Issue by ArcticSnowman** [ether/ep_headings2#53] opened 2021-11-18 17:49 UTC
Clearing authorship colors fails when no text selected in PAD if there is a HEADING on the first line

![image](https://user-images.githubusercontent.com/13837922/142436957-c9614353-94a5-4546-9c93-17365d6d48ee.png)

### Versions
etherpad-lite: 1.8.14

### Plugins:
![image](https://user-images.githubusercontent.com/13837922/142437234-533039e8-f2cb-4e90-a863-7ca8f879c3b7.png)

**Comment by ArcticSnowman** [comment] 2021-11-18 17:50
Example: https://video.etherpad.com/p/pr3FAt5r9VBV8fglGm7H

**Comment by rhansen** [comment] 2021-11-19 07:40
Duplicate of ether/etherpad-lite#5128

**Closed by rhansen** 2021-11-19 07:40 UTC
